---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - octechsolutionsorg/dependabot-devops-team
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    reviewers:
      - octechsolutionsorg/dependabot-devops-team
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    reviewers:
      - octechsolutionsorg/dependabot-devops-team
